import localFont from "next/font/local";
import "./globals.css";
import { Providers, ProvidersMantine } from "@/mantine/Provider";
import Header from "@/components/header/Header";
import { ProductProvider } from "@/provider/ProviderContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Check if the current route is the root

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ProductProvider>
            {/* <Header /> */}
            {children}
          </ProductProvider>
        </Providers>
      </body>
    </html>
  );
}
